import { Image } from "react-native";

import type { BattleAssetSet } from "./types";

function localUri(moduleId: number) {
  try {
    return Image.resolveAssetSource(moduleId)?.uri || null;
  } catch {
    return null;
  }
}

const SCENARIO_ASSETS: Record<string, Partial<BattleAssetSet>> = {
  beach: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/sky_beach_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/sky_beach_day.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/background_beach_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/background_beach_day.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/background_beach_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/ground_beach_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/ground_beach_day.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/ground_beach_day.png")),
    platformPlayer: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/platform_player_beach.png")),
    platformEnemy: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/platform_enemy_beach.png")),
    platformPlayerNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/platform_player_beach.png")),
    platformEnemyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/beach/platform_enemy_beach.png")),
  },
  cave: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/cave/sky_cave_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/cave/sky_cave_day.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/cave/background_cave_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/cave/background_cave_day.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/cave/background_cave_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/cave/ground_cave_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/cave/ground_cave_day.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/cave/ground_cave_day.png")),
    platformPlayer: null,
    platformEnemy: null,
    platformPlayerNight: null,
    platformEnemyNight: null,
  },
  city: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/sky_city_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/sky_city_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/background_city_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/background_city_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/background_city_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/ground_city_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/ground_city_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/ground_city_day.png")),
    platformPlayer: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/platform_player_city.png")),
    platformEnemy: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/platform_enemy_city.png")),
    platformPlayerNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/platform_player_city.png")),
    platformEnemyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/city/platform_enemy_city.png")),
  },
  desert: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/sky_desert_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/sky_desert_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/background_desert_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/background_desert_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/background_desert_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/ground_desert_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/ground_desert_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/ground_desert_day.png")),
    platformPlayer: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/platform_player_desert.png")),
    platformEnemy: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/platform_enemy_desert.png")),
    platformPlayerNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/platform_player_desert.png")),
    platformEnemyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/desert/platform_enemy_desert.png")),
  },
  dojo: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/sky_dojo_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/sky_dojo_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/background_dojo_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/background_dojo_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/background_dojo_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/ground_dojo_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/ground_dojo_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/ground_dojo_day.png")),
    platformPlayer: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/platform_player_dojo.png")),
    platformEnemy: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/platform_enemy_dojo.png")),
    platformPlayerNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/platform_player_dojo.png")),
    platformEnemyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/dojo/platform_enemy_dojo.png")),
  },
  forest: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/florest/sky_forest_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/florest/sky_forest_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/florest/background_forest_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/florest/background_forest_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/florest/background_forest_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/florest/ground_forest_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/florest/ground_forest_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/florest/ground_forest_day.png")),
    platformPlayer: null,
    platformEnemy: null,
    platformPlayerNight: null,
    platformEnemyNight: null,
  },
  grassland: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/grassland/sky_grasslands_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/grassland/sky_grasslands_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/grassland/background_grasslands_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/grassland/background_grasslands_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/grassland/background_grasslands_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/grassland/GROUND_DAY.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/grassland/ground_grasslands_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/grassland/GROUND_DAY.png")),
    platformPlayer: null,
    platformEnemy: null,
    platformPlayerNight: null,
    platformEnemyNight: null,
  },
  lake: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/sky_lake_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/sky_lake_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/background_lake_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/background_lake_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/background_lake_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/ground_lake_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/ground_lake_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/ground_lake_day.png")),
    platformPlayer: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/platform_player_lake.png")),
    platformEnemy: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/platform_enemy_lake.png")),
    platformPlayerNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/platform_player_lake.png")),
    platformEnemyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/lake/platform_enemy_lake.png")),
  },
  mountain: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/sky_mountain_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/sky_mountain_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/background_mountain_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/background_mountain_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/background_mountain_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/ground_mountain_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/ground_mountain_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/ground_mountain_day.png")),
    platformPlayer: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/platform_player_mountain.png")),
    platformEnemy: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/platform_enemy_mountain.png")),
    platformPlayerNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/platform_player_mountain.png")),
    platformEnemyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/montain/platform_enemy_mountain.png")),
  },
  river: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/sky_river_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/sky_river_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/background_river_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/background_river_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/background_river_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/ground_river_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/ground_river_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/ground_river_day.png")),
    platformPlayer: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/platform_player_river.png")),
    platformEnemy: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/platform_enemy_river.png")),
    platformPlayerNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/platform_player_river.png")),
    platformEnemyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/river/platform_enemy_river.png")),
  },
  ruins: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/sky_ruins_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/sky_ruins_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/background_ruins_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/background_ruins_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/background_ruins_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/ground_ruins_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/ground_ruins_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/ground_ruins_day.png")),
    platformPlayer: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/platform_player_ruins.png")),
    platformEnemy: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/platform_enemy_ruins.png")),
    platformPlayerNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/platform_player_ruins.png")),
    platformEnemyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/ruinas/platform_enemy_ruins.png")),
  },
  snow: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/sky_snow_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/sky_snow_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/background_snow_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/background_snow_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/background_snow_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/ground_snow_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/ground_snow_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/ground_snow_day.png")),
    platformPlayer: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/platform_player_snow.png")),
    platformEnemy: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/platform_enemy_snow.png")),
    platformPlayerNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/platform_player_snow.png")),
    platformEnemyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/snow/platform_enemy_snow.png")),
  },
  swamp: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/sky_swamp_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/sky_swamp_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/background_swamp_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/background_swamp_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/background_swamp_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/ground_swamp_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/ground_swamp_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/ground_swamp_day.png")),
    platformPlayer: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/platform_player_swamp.png")),
    platformEnemy: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/platform_enemy_swamp.png")),
    platformPlayerNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/platform_player_swamp.png")),
    platformEnemyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/swamp/platform_enemy_swamp.png")),
  },
  vocanion: {
    skyDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/sky_vocanion_day.png")),
    skyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/sky_vocanion_night.png")),
    backgroundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/background_vocanion_day.png")),
    backgroundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/background_vocanion_night.png")),
    background: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/background_vocanion_day.png")),
    groundDay: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/ground_vocanion_day.png")),
    groundNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/ground_vocanion_night.png")),
    ground: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/ground_vocanion_day.png")),
    platformPlayer: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/platform_player_vocanion.png")),
    platformEnemy: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/platform_enemy_vocanion.png")),
    platformPlayerNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/platform_player_vocanion.png")),
    platformEnemyNight: localUri(require("../../../assets/images/biomas/assets_cenario_battle/vocanion/platform_enemy_vocanion.png")),
  },
};

export function getScenarioAssets(scenario: string): Partial<BattleAssetSet> | null {
  const key = String(scenario || "").trim().toLowerCase();
  return SCENARIO_ASSETS[key] || null;
}
